name: Deploy Famiree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, mysql
          
      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader
        
      - name: Setup Application
        run: |
          cp config/app.php.default config/app.php
          
      - name: 📂 Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: ${{ if0_38351075! }}
          password: ${{ Z1uyqFSkUIoVNV  }}
          server-dir: /htdocs/
